GET http://localhost:3000/projects

###
GET http://localhost:3000/projects/d1d0e784-2c12-4cf9-b59a-875c3c807629

###
# @name createProject
POST http://localhost:3000/projects
Content-Type: application/json

{
  "name": "Projeto 1",
  "description": "Description 1"
}

###
@project_id = {{createProject.response.body.id}}

###
PATCH http://localhost:3000/projects/{{project_id}}
Content-Type: application/json

{
  "name": "Projeto 2",
  "description": "Description 2"
}

###
POST http://localhost:3000/projects/{{project_id}}/start
Content-Type: application/json

{
  "started_at": "2023-10-10"
}